apiVersion: v1
kind: Service
metadata:
  name: freeradius
  namespace: iron-claw
spec:
  type: ClusterIP
  selector:
    app: freeradius
  ports:
    - name: auth
      port: 1812
      targetPort: 1812
      protocol: UDP
    - name: acct
      port: 1813
      targetPort: 1813
      protocol: UDP
