#
#	RADIUS clients configuration for iron-claw
#
#	The iron-claw scraper authenticates from localhost.
#

client localhost {
	ipaddr = 127.0.0.1
	secret = testing123
	nastype = other
	shortname = iron-claw
}

client localhost_ipv6 {
	ipv6addr = ::1
	secret = testing123
	nastype = other
	shortname = iron-claw-v6
}
